Try to fix playwright by removing extra Rust cache
Otherwise, all dependencies seem to be missing:

```
   Compiling gitbutler-oxidize v0.0.0 (/home/runner/work/gitbutler/gitbutler/crates/gitbutler-oxidize)
   Compiling gitbutler-fs v0.0.0 (/home/runner/work/gitbutler/gitbutler/crates/gitbutler-fs)
   Compiling gitbutler-id v0.0.0 (/home/runner/work/gitbutler/gitbutler/crates/gitbutler-id)
   Compiling gitbutler-tagged-string v0.0.0 (/home/runner/work/gitbutler/gitbutler/crates/gitbutler-tagged-string)
error[E0463]: can't find crate for `gix`
 --> crates/gitbutler-oxidize/src/lib.rs:4:5
  |
4 | use gix::bstr::ByteSlice;
  |     ^^^ can't find crate

error[E0463]: can't find crate for `gix`
 --> crates/gitbutler-fs/src/lib.rs:9:5
```