fix(but): avoid paging for stage to not break prompting
The pager makes prompting via crossterm impossible as crossterm can't
determine the cursor position. You get output like this:

```
Waiting for data... (^X or interrupt to abort)
Error: Failed to stage.

Caused by:
    0: failed to setup picker tui
    1: The cursor position could not be read within a normal duration
```