fix(but): make name validation in `but branch new` strict
This solves several problems in `but branch new`:

1. The command would previously normalize branch names automatically,
which is unexpected for a CLI. If you type `but branch new 'my branch'`
and get a success back, you expect there to be a branch called 'my
branch'. But the actual name of the new branch was normalized to
'my-branch'. The new behavior is to reject any non-normalized name and
print hint with the normalized name instead.
2. Branch creation was idempotent for branches already applied in the
workspace, which was very confusing as the CLI claimed to have
successfully created a new branch while in fact it had done nothing.
Such branch creation is now clearly rejected, which also falls in line
with how Git handles such a situation.
3. Various obtuse error messages have been improved. For example, when
creating a new branch with a name that already existed and anchoring it
to anywhere, you'd get an error like this::

```
Error: The reference "refs/heads/<name>" should have content b54c2567115498ffcb87b31a4f1f95f0bead2546, actual content was 6078e6bb61d3b1ac4f35f57f05e2cce3382359ff
```

The new error just says that the branch already exists.